/**
 * Gera páginas estáticas em dist/posts/{id}/index.html para cada post.
 *
 * IMPORTANTE (SEO): além das meta tags OG, este script PRÉ-RENDERIZA o conteúdo
 * completo do artigo (markdown -> HTML) dentro de <div id="root">. Assim o
 * Googlebot recebe o texto real do post no HTML cru, sem precisar executar
 * JavaScript. Ao montar, o React (createRoot) substitui o conteúdo de #root
 * pelo app normal — os usuários veem a SPA, o Google indexa o conteúdo estático.
 *
 * Também injeta window.__INITIAL_POST_ID__ para o React abrir o post direto.
 * Executado após `vite build` no script "build" do package.json.
 */
import fs from "fs";
import path from "path";
import { marked } from "marked";
import { stripLeadingTitleAndSummary } from "../src/lib/postContent";

const BASE_URL = "https://leonardodebs.github.io/tech-insights-blog";
const DIST_DIR = path.resolve(process.cwd(), "dist");
const POSTS_PATH = path.resolve(process.cwd(), "src/data/posts.json");

interface Post {
  id: string;
  title: string;
  excerpt: string;
  content: string;
  date: string;
  category: string;
  tags: string[];
}

const posts: Post[] = JSON.parse(fs.readFileSync(POSTS_PATH, "utf-8"));

// Read the base index.html generated by Vite
const baseHtml = fs.readFileSync(path.join(DIST_DIR, "index.html"), "utf-8");

function escapeAttr(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Remove meta tags genéricas do index.html base para não duplicar com as do post
// Remove do index.html base as tags genéricas da homepage, para não conflitar
// com as tags específicas do post injetadas abaixo. É CRÍTICO remover o
// canonical genérico: se ficasse, a página do post teria dois canonicals
// (o da home + o do post), e o Google não indexaria a URL correta.
function stripGenericMeta(html: string): string {
  return html
    .replace(/<meta\s+name="description"[^>]*>/gi, "")
    .replace(/<meta\s+property="og:title"[^>]*>/gi, "")
    .replace(/<meta\s+property="og:description"[^>]*>/gi, "")
    .replace(/<meta\s+property="og:type"[^>]*>/gi, "")
    .replace(/<meta\s+property="og:url"[^>]*>/gi, "")
    .replace(/<meta\s+property="twitter:url"[^>]*>/gi, "")
    .replace(/<link\s+rel="canonical"[^>]*>/gi, "");
}

// Lista de links estáticos (crawlável) para os posts mais recentes
function relatedLinks(list: Post[], excludeId?: string): string {
  const items = list
    .filter(p => p.id !== excludeId)
    .slice(0, 12)
    .map(p => `<li><a href="${BASE_URL}/posts/${p.id}/">${escapeHtml(p.title)}</a></li>`)
    .join("\n        ");
  return `<nav aria-label="Outros posts">
      <h2>Leia também</h2>
      <ul>
        ${items}
      </ul>
    </nav>`;
}

let generated = 0;

for (const post of posts) {
  const postDir = path.join(DIST_DIR, "posts", post.id);
  fs.mkdirSync(postDir, { recursive: true });

  const escaped = {
    title: escapeAttr(post.title),
    excerpt: escapeAttr(post.excerpt),
  };

  const postUrl = `${BASE_URL}/posts/${post.id}/`;

  // Renderiza o corpo do artigo (conteúdo confiável — gerado por nós).
  // Remove o título e o resumo do início do content, pois são renderizados
  // separadamente abaixo (a partir de post.title e post.excerpt) — senão
  // apareceriam duplicados.
  const articleBodyHtml = marked.parse(
    stripLeadingTitleAndSummary(post.content || ""),
    { async: false }
  ) as string;

  const tagsHtml = post.tags
    .map(t => `<span class="tag">#${escapeHtml(t)}</span>`)
    .join(" ");

  // Conteúdo estático dentro de #root — o React substitui ao montar.
  const prerendered = `<article>
      <p class="category">${escapeHtml(post.category)} · ${new Date(post.date).toLocaleDateString("pt-BR")}</p>
      <h1>${escapeHtml(post.title)}</h1>
      <blockquote>${escapeHtml(post.excerpt)}</blockquote>
      ${articleBodyHtml}
      <div class="tags">${tagsHtml}</div>
    </article>
    ${relatedLinks(posts, post.id)}
    <p><a href="${BASE_URL}/">Voltar para a página inicial</a></p>`;

  let html = stripGenericMeta(baseHtml)
    .replace(
      /<title>.*?<\/title>/,
      `<title>${escaped.title} | Tech Insights Blog</title>`
    )
    .replace(
      "</head>",
      `  <meta name="description" content="${escaped.excerpt}"/>
  <meta property="og:type" content="article"/>
  <meta property="og:title" content="${escaped.title}"/>
  <meta property="og:description" content="${escaped.excerpt}"/>
  <meta property="og:url" content="${postUrl}"/>
  <meta property="og:site_name" content="Tech Insights Blog"/>
  <meta name="twitter:card" content="summary"/>
  <meta name="twitter:url" content="${postUrl}"/>
  <meta name="twitter:title" content="${escaped.title}"/>
  <meta name="twitter:description" content="${escaped.excerpt}"/>
  <link rel="canonical" href="${postUrl}"/>
  <script>window.__INITIAL_POST_ID__ = "${post.id}";</script>
</head>`
    )
    .replace('<div id="root"></div>', `<div id="root">${prerendered}</div>`);

  fs.writeFileSync(path.join(postDir, "index.html"), html, "utf-8");
  generated++;
}

// Homepage: injeta links estáticos para TODOS os posts dentro de #root,
// para o Googlebot descobrir cada URL a partir da home (que já está indexada).
const homepageLinks = `<nav aria-label="Todos os posts">
      <h1>Tech Insights Blog</h1>
      <ul>
        ${posts.map(p => `<li><a href="${BASE_URL}/posts/${p.id}/">${escapeHtml(p.title)}</a></li>`).join("\n        ")}
      </ul>
    </nav>`;
const homepageHtml = baseHtml.replace('<div id="root"></div>', `<div id="root">${homepageLinks}</div>`);
fs.writeFileSync(path.join(DIST_DIR, "index.html"), homepageHtml, "utf-8");

console.log(`✅ ${generated} páginas de post pré-renderizadas em dist/posts/`);
console.log(`✅ Homepage com ${posts.length} links estáticos para indexação.`);
