/**
 * Gera páginas estáticas em dist/posts/{id}/index.html para cada post.
 * Cada página injeta window.__INITIAL_POST_ID__ para o React abrir o post diretamente.
 * Isso permite que links diretos para posts funcionem com meta tags OG corretas (SEO/compartilhamento).
 * Executado após `vite build` no script "build" do package.json.
 */
import fs from "fs";
import path from "path";

const BASE_URL = "https://leonardodebs.github.io/tech-insights-blog";
const DIST_DIR = path.resolve(process.cwd(), "dist");
const POSTS_PATH = path.resolve(process.cwd(), "src/data/posts.json");

interface Post {
  id: string;
  title: string;
  excerpt: string;
  date: string;
  category: string;
  tags: string[];
}

const posts: Post[] = JSON.parse(fs.readFileSync(POSTS_PATH, "utf-8"));

// Read the base index.html generated by Vite
const baseHtml = fs.readFileSync(path.join(DIST_DIR, "index.html"), "utf-8");

let generated = 0;

for (const post of posts) {
  const postDir = path.join(DIST_DIR, "posts", post.id);
  fs.mkdirSync(postDir, { recursive: true });

  const escaped = {
    title: post.title.replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;"),
    excerpt: post.excerpt.replace(/"/g, "&quot;").replace(/</g, "&lt;").replace(/>/g, "&gt;"),
  };

  const postUrl = `${BASE_URL}/posts/${post.id}/`;

  // Replace <title> and inject OG meta tags + __INITIAL_POST_ID__
  let html = baseHtml
    .replace(
      /<title>.*?<\/title>/,
      `<title>${escaped.title} | Tech Insights Blog</title>`
    )
    .replace(
      "</head>",
      `  <meta name="description" content="${escaped.excerpt}"/>
  <meta property="og:type" content="article"/>
  <meta property="og:title" content="${escaped.title}"/>
  <meta property="og:description" content="${escaped.excerpt}"/>
  <meta property="og:url" content="${postUrl}"/>
  <meta property="og:site_name" content="Tech Insights Blog"/>
  <meta name="twitter:card" content="summary"/>
  <meta name="twitter:title" content="${escaped.title}"/>
  <meta name="twitter:description" content="${escaped.excerpt}"/>
  <link rel="canonical" href="${postUrl}"/>
  <script>window.__INITIAL_POST_ID__ = "${post.id}";</script>
</head>`
    );

  fs.writeFileSync(path.join(postDir, "index.html"), html, "utf-8");
  generated++;
}

console.log(`✅ ${generated} páginas de post geradas em dist/posts/`);
